backend:
    name: git-gateway
    #name: test-repo
    branch: master
local_backend: true
media_folder: public/images
public_folder: /images
collections:
    - name: "meta"
      label: "Meta"
      delete: false
      editor:
          preview: false
      files:
          - name: "authors"
            label: "Authors"
            file: "content/authors.yml"
            description: "Author descriptions"
            fields:
                - name: authors
                  label: Authors
                  label_singular: "Author"
                  widget: list
                  fields:
                      - label: "Slug"
                        name: "slug"
                        widget: "string"
                        hint: "The part of a URL identifies the author"
                      - label: "Name"
                        name: "name"
                        widget: "string"
                        hint: "First and Last"
                      - label: "Introduction"
                        name: "introduction"
                        widget: "text"
          - name: "tags"
            label: "Tags"
            file: "content/tags.yml"
            description: "List of tags"
            fields:
                - name: tags
                  label: Tags
                  label_singular: "Tag"
                  widget: list
                  fields:
                      - label: "Slug"
                        name: "slug"
                        widget: "string"
                        hint: "The part of a URL identifies the tag"
                      - label: "Display Name"
                        name: "name"
                        widget: "string"
                        hint: "Tag name for displaying on the site"

    - name: "posts"
      label: "Posts"
      folder: "content/posts"
      extension: "md"
      format: "frontmatter"
      create: true
      slug: "{{slug}}"
      identifier_field: slug
      summary: "{{title}}"
      fields:
          - label: "Slug"
            name: "slug"
            widget: "string"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Publish Date"
            name: "date"
            widget: "datetime"
            format: "YYYY-MM-DD"
            dateFormat: "YYYY-MM-DD"
            timeFormat: false
          - label: Author
            name: "author"
            widget: relation
            collection: "meta"
            file: "authors"
            searchFields:
                - "authors.*.name"
            displayFields:
                - "authors.*.name"
            valueField: "authors.*.slug"
          - label: Tags
            label_singular: "Tag"
            name: "tags"
            widget: list
            summary: "{{fields.tag}}"
            field:
                label: Tag
                name: tag
                widget: relation
                collection: "meta"
                file: "tags"
                searchFields:
                    - "tags.*.name"
                displayFields:
                    - "tags.*.name"
                valueField: "tags.*.slug"
          - label: "Body"
            name: "body"
            widget: "markdown"
          - label: "Cover Image"
            name: "coverImage"
            widget: "image"
            # default: "/uploads/chocolate-dogecoin.jpg"
            # media_library:
            #     config:
            #         multiple: true
